env:
  jquery: true
  browser: true
  node: true
  es6: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 2017
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - never
  array-bracket-spacing:
    - error
    - never
  block-spacing:
    - error
    - always
  no-eval:
   - error
  no-var:
   - error
  camelcase:
   - error
  keyword-spacing:
   - error
  max-depth:
   - error
   - 4
  no-console:
   - off
  brace-style:
   - error
   - 1tbs
  comma-spacing:
   - error
  func-call-spacing:
   - error
